
import "./globals.css";
import { Poppins } from "next/font/google";
import ConditionalLayout from "@/components/layout/ConditionalLayout";
import { ReduxProvider } from "@/store/provider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
          <body
          //  className="min-h-screen flex flex-col antialiased"
          className={`${poppins.variable} font-sans min-h-screen flex flex-col `}
           >
          <ReduxProvider>

                    <ConditionalLayout>{children}

                    <ToastContainer
          position="top-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={true}
          closeOnClick
          pauseOnHover
          draggable
          theme="light"
        />
                    </ConditionalLayout>

      
                    </ReduxProvider>
         {/* <Header/>
         <main className="flex-1">
          {children}
        </main>
      <Footer/> */}
      </body>
    </html>
  );
}
