import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import { Poppins } from "next/font/google";
import ConditionalLayout from "@/components/layout/ConditionalLayout";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
          <body
          //  className="min-h-screen flex flex-col antialiased"
          className={`${poppins.variable} font-sans min-h-screen flex flex-col `}
           >
                    <ConditionalLayout>{children}</ConditionalLayout>
         {/* <Header/>
         <main className="flex-1">
          {children}
        </main>
      <Footer/> */}
      </body>
    </html>
  );
}
